// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";

function HomeIcon(Props) {
  var width = Props.width;
  var height = Props.height;
  var fill = Props.fill;
  var stroke = Props.stroke;
  var tmp = {
    viewBox: "0 0 460.3 460.3"
  };
  if (height !== undefined) {
    tmp.height = Caml_option.valFromOption(height);
  }
  if (width !== undefined) {
    tmp.width = Caml_option.valFromOption(width);
  }
  if (fill !== undefined) {
    tmp.fill = Caml_option.valFromOption(fill);
  }
  if (stroke !== undefined) {
    tmp.stroke = Caml_option.valFromOption(stroke);
  }
  return React.createElement("svg", tmp, React.createElement("path", {
                  d: "M230.1 121L66 256.2l-.2.8-.1.9v137c0 5 1.8 9.3 5.4 12.9 3.6 3.6 8 5.4 12.9 5.4h109.6V303.7h73.1v109.6h109.6c5 0 9.3-1.8 12.9-5.4 3.6-3.6 5.4-8 5.4-12.9V258a4 4 0 00-.3-1.7L230.1 120.9z"
                }), React.createElement("path", {
                  d: "M457.1 225.4l-62.5-52V57a8.9 8.9 0 00-9.1-9.1h-54.9c-2.6 0-4.8.8-6.5 2.5a8.9 8.9 0 00-2.6 6.6v55.7l-69.7-58.3c-6-5-13.3-7.4-21.6-7.4-8.4 0-15.7 2.5-21.7 7.4L3.2 225.4a8.3 8.3 0 00-3.2 6.2c-.2 2.5.5 4.8 2 6.7l17.7 21.1a9.7 9.7 0 006 3.2c2.3.1 4.6-.5 6.9-2L230 95.8l197.6 164.8c1.5 1.3 3.5 2 6 2h.9a9.8 9.8 0 006-3.2l17.7-21.1c1.5-2 2.2-4.2 2-6.7a8.3 8.3 0 00-3.2-6.2z"
                }));
}

var make = HomeIcon;

export {
  make ,
  
}
/* react Not a pure module */
