// Generated by ReScript, PLEASE EDIT WITH CARE


function getItemsForCategory(category) {
  return [
          {
            name: "Kuta beach",
            price: 50,
            picture: "/assets/img/beach-1.webp",
            sandiness: /* Coarse */0
          },
          {
            name: "Jimbaran",
            price: 46,
            picture: "/assets/img/beach-2.webp",
            sandiness: /* Soft */1
          }
        ];
}

export {
  getItemsForCategory ,
  
}
/* No side effect */
