// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as AppModuleCss from "./App.module.css";
import * as Header$RescriptViteReactWindicss from "./Header.bs.js";
import * as Navbar$RescriptViteReactWindicss from "./Navbar.bs.js";
import * as Categories$RescriptViteReactWindicss from "./Categories.bs.js";

var styles = AppModuleCss;

function App(Props) {
  return React.createElement("div", {
              className: "bg-gradient-to-b from-hex-2d3436 to-hex-23272a w-full h-full p-16"
            }, React.createElement(Header$RescriptViteReactWindicss.make, {}), React.createElement(Categories$RescriptViteReactWindicss.make, {}), React.createElement(Navbar$RescriptViteReactWindicss.make, {}));
}

var make = App;

export {
  styles ,
  make ,
  
}
/* styles Not a pure module */
