// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Recipes$RescriptViteReactWindicss from "./Recipes.bs.js";

function App(Props) {
  return React.createElement("div", {
              className: "m-auto h-screen bg-gradient-to-br from-yellow-400 to-orange-500 p-32"
            }, React.createElement(Recipes$RescriptViteReactWindicss.make, {}));
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
