// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as BbqIcon$RescriptViteReactWindicss from "./img/components/SVGSrc/img/bbqIcon.bs.js";
import * as BeachIcon$RescriptViteReactWindicss from "./img/components/SVGSrc/img/beachIcon.bs.js";

var categories = [
  {
    name: "Beach",
    namePl: "Beaches",
    icon: React.createElement(BeachIcon$RescriptViteReactWindicss.make, {
          width: "48px"
        })
  },
  {
    name: "Barbeque",
    namePl: "Barbeques",
    icon: React.createElement(BbqIcon$RescriptViteReactWindicss.make, {
          width: "48px"
        })
  }
];

export {
  categories ,
  
}
/* categories Not a pure module */
