// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

var title = "Discover";

var subtitle = "Explore the best places in the world";

function Header(Props) {
  return React.createElement("div", {
              className: "p-0"
            }, React.createElement("h2", {
                  className: "text-gray-100 text-5xl my-4"
                }, title), React.createElement("h3", {
                  className: "text-gray-300 text-xl"
                }, subtitle));
}

var make = Header;

export {
  title ,
  subtitle ,
  make ,
  
}
/* react Not a pure module */
