// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as HomeIcon$RescriptViteReactWindicss from "./img/components/SVGSrc/img/homeIcon.bs.js";

function Navbar(Props) {
  return React.createElement("div", {
              className: "bg-hex-2a2e31 p-4 px-16 mt-72 border-2 border-hex-373b3f rounded-xl flex justify-between"
            }, React.createElement("span", {
                  className: "relative"
                }, React.createElement(HomeIcon$RescriptViteReactWindicss.make, {
                      width: "32px",
                      height: "32px",
                      fill: "#eceeec"
                    }), React.createElement("span", {
                      className: "w-2 h-2 bg-hex-ebeded rounded-xl absolute top-35px right-12px"
                    })), React.createElement(HomeIcon$RescriptViteReactWindicss.make, {
                  width: "32px",
                  height: "32px",
                  fill: "#b3b6ba"
                }), React.createElement(HomeIcon$RescriptViteReactWindicss.make, {
                  width: "32px",
                  height: "32px",
                  fill: "#b3b6ba"
                }), React.createElement(HomeIcon$RescriptViteReactWindicss.make, {
                  width: "32px",
                  height: "32px",
                  fill: "#b3b6ba"
                }));
}

var make = Navbar;

export {
  make ,
  
}
/* react Not a pure module */
