// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";
import * as Recipe$RescriptViteReactWindicss from "./Recipe.bs.js";

var exampleRecipes = [
  /* SolidFoodRecipe */{
    _0: {
      name: "Cauliflower Fried Rice",
      timeToMake: 20,
      servings: 4,
      image: "https://picsum.photos/64/64"
    }
  },
  /* SolidFoodRecipe */{
    _0: {
      name: "Italian Wedding Soup",
      timeToMake: 60,
      servings: 1,
      image: "https://picsum.photos/64/64"
    }
  }
];

function Recipes(Props) {
  return React.createElement("div", {
              className: "p-8 w-1/2 bg-white mx-auto rounded-xl shadow-lg"
            }, React.createElement("ul", {
                  className: "divide-y divide-gray-100"
                }, Belt_Array.mapWithIndex(exampleRecipes, (function (ind, recipe) {
                        return React.createElement(Recipe$RescriptViteReactWindicss.make, {
                                    recipe: recipe,
                                    key: String(ind)
                                  });
                      }))));
}

var make = Recipes;

export {
  exampleRecipes ,
  make ,
  
}
/* react Not a pure module */
