// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Recipe$FoodRecipe(Props) {
  var name = Props.name;
  var timeToMake = Props.timeToMake;
  var servings = Props.servings;
  var image = Props.image;
  return React.createElement("article", {
              className: "p-4 flex space-x-4"
            }, React.createElement("img", {
                  className: "flex-none w-18 h-18 rounded-lg bg-gray-100",
                  src: image
                }), React.createElement("div", {
                  className: "min-w-0 relative flex-auto"
                }, React.createElement("h2", {
                      className: "text-lg font-semibold text-black mb-0.5"
                    }, name), React.createElement("dl", {
                      className: "flex flex-wrap text-sm font-medium whitespace-pre"
                    }, React.createElement("div", undefined, React.createElement("dt", {
                              className: "sr-only"
                            }, "Time"), React.createElement("dd", undefined, React.createElement("abbr", {
                                  title: "" + timeToMake + " minutes"
                                }, "" + timeToMake + " m"))), React.createElement("div", undefined, React.createElement("dt", {
                              className: "sr-only"
                            }, "Servings"), React.createElement("dd", undefined, "" + servings + " servings")))));
}

var FoodRecipe = {
  make: Recipe$FoodRecipe
};

function Recipe(Props) {
  var recipe = Props.recipe;
  var match = recipe._0;
  return React.createElement(Recipe$FoodRecipe, {
              name: match.name,
              timeToMake: match.timeToMake,
              servings: match.servings,
              image: match.image
            });
}

var make = Recipe;

export {
  FoodRecipe ,
  make ,
  
}
/* react Not a pure module */
